INSERT INTO startup_resources (
  name, category, description, website, city, state, lat, lng, location, stage_fit, industry_fit, tags
)
VALUES
  (
    'Silicon Slopes',
    'community',
    'Statewide startup community with events, networking, and founder programs.',
    'https://siliconslopes.com',
    'Lehi',
    'UT',
    40.3916,
    -111.8508,
    ST_SetSRID(ST_MakePoint(-111.8508, 40.3916), 4326),
    ARRAY['idea','validation','mvp','launched'],
    ARRAY['saas','ai','fintech'],
    ARRAY['community','networking','founders']
  ),
  (
    'Utah Tech Week',
    'event',
    'Multi-day startup ecosystem event connecting founders, investors, and operators.',
    'https://www.utahtechweek.com',
    'Salt Lake City',
    'UT',
    40.7608,
    -111.8910,
    ST_SetSRID(ST_MakePoint(-111.8910, 40.7608), 4326),
    ARRAY['idea','validation','mvp','launched','traction'],
    ARRAY['saas','ai','healthtech','consumer'],
    ARRAY['events','networking']
  ),
  (
    'UVU Business Resource Center',
    'university',
    'University-supported business development and startup support programs.',
    'https://www.uvu.edu/woodbury/brc',
    'Orem',
    'UT',
    40.2783,
    -111.7156,
    ST_SetSRID(ST_MakePoint(-111.7156, 40.2783), 4326),
    ARRAY['idea','validation'],
    ARRAY['services','saas','consumer'],
    ARRAY['mentorship','education']
  ),
  (
    'BYU Rollins Center',
    'university',
    'BYU entrepreneurship programs, mentorship, and venture support.',
    'https://marriott.byu.edu/rollins-center',
    'Provo',
    'UT',
    40.2500,
    -111.6493,
    ST_SetSRID(ST_MakePoint(-111.6493, 40.2500), 4326),
    ARRAY['idea','validation','mvp'],
    ARRAY['saas','consumer','edtech'],
    ARRAY['mentorship','student-founders']
  ),
  (
    'Lassonde Entrepreneur Institute',
    'university',
    'University of Utah entrepreneurship institute with startup programs and founder support.',
    'https://lassonde.utah.edu',
    'Salt Lake City',
    'UT',
    40.7649,
    -111.8421,
    ST_SetSRID(ST_MakePoint(-111.8421, 40.7649), 4326),
    ARRAY['idea','validation','mvp'],
    ARRAY['saas','consumer','healthtech'],
    ARRAY['incubation','mentors']
  ),
  (
    'Kiln',
    'coworking',
    'Coworking and collaboration space for startups and remote teams.',
    'https://kiln.com',
    'Lehi',
    'UT',
    40.4303,
    -111.8932,
    ST_SetSRID(ST_MakePoint(-111.8932, 40.4303), 4326),
    ARRAY['idea','validation','mvp','launched'],
    ARRAY['saas','ai','services'],
    ARRAY['coworking','community']
  ),
  (
    'RevRoad',
    'accelerator',
    'Operator-led startup accelerator with growth support and advisor network.',
    'https://revroad.com',
    'Provo',
    'UT',
    40.2338,
    -111.6585,
    ST_SetSRID(ST_MakePoint(-111.6585, 40.2338), 4326),
    ARRAY['validation','mvp','launched'],
    ARRAY['saas','consumer','marketplace'],
    ARRAY['accelerator','growth']
  ),
  (
    'BoomStartup',
    'accelerator',
    'Seed-stage accelerator focused on mentor-driven company building.',
    'https://boomstartup.com',
    'Salt Lake City',
    'UT',
    40.7578,
    -111.8762,
    ST_SetSRID(ST_MakePoint(-111.8762, 40.7578), 4326),
    ARRAY['validation','mvp','launched'],
    ARRAY['saas','ai','healthtech'],
    ARRAY['accelerator','fundraising']
  ),
  (
    '47G',
    'community',
    'Innovation ecosystem focused on strategic industry clusters in Utah.',
    'https://47g.org',
    'Salt Lake City',
    'UT',
    40.7584,
    -111.8760,
    ST_SetSRID(ST_MakePoint(-111.8760, 40.7584), 4326),
    ARRAY['validation','mvp','launched','traction'],
    ARRAY['aerospace','energy','defense','advanced-manufacturing'],
    ARRAY['community','industry-network']
  ),
  (
    'Utah Innovation Center',
    'incubator',
    'Incubator support for early-stage companies and commercialization.',
    'https://www.utahinnovationcenter.com',
    'Kaysville',
    'UT',
    41.0381,
    -111.9386,
    ST_SetSRID(ST_MakePoint(-111.9386, 41.0381), 4326),
    ARRAY['idea','validation','mvp'],
    ARRAY['saas','biotech','hardware'],
    ARRAY['incubator','mentorship']
  ),
  (
    'World Trade Center Utah',
    'government',
    'Export assistance and global market support for Utah companies.',
    'https://wtcutah.com',
    'Salt Lake City',
    'UT',
    40.7614,
    -111.8880,
    ST_SetSRID(ST_MakePoint(-111.8880, 40.7614), 4326),
    ARRAY['launched','traction','scale'],
    ARRAY['saas','consumer','manufacturing'],
    ARRAY['international','expansion']
  ),
  (
    'MountainWest Capital Network',
    'community',
    'Capital and growth community supporting scaling companies in the region.',
    'https://mwcn.org',
    'Salt Lake City',
    'UT',
    40.7604,
    -111.8914,
    ST_SetSRID(ST_MakePoint(-111.8914, 40.7604), 4326),
    ARRAY['mvp','launched','traction','fundraising'],
    ARRAY['saas','fintech','healthtech'],
    ARRAY['capital','network']
  ),
  (
    'Kickstart Fund',
    'investor',
    'Early-stage venture capital fund for high-growth technology startups.',
    'https://kickstartfund.com',
    'Cottonwood Heights',
    'UT',
    40.6197,
    -111.8102,
    ST_SetSRID(ST_MakePoint(-111.8102, 40.6197), 4326),
    ARRAY['mvp','launched','traction','fundraising'],
    ARRAY['saas','ai','fintech'],
    ARRAY['vc','fundraising']
  ),
  (
    'Peterson Ventures',
    'investor',
    'Venture fund investing in SaaS and technology startups.',
    'https://petersonventures.com',
    'Salt Lake City',
    'UT',
    40.7613,
    -111.8912,
    ST_SetSRID(ST_MakePoint(-111.8912, 40.7613), 4326),
    ARRAY['mvp','launched','traction','fundraising'],
    ARRAY['saas','developer-tools','security'],
    ARRAY['vc','b2b']
  ),
  (
    'Album VC',
    'investor',
    'Early-stage VC fund focused on software startups in the Mountain West.',
    'https://album.vc',
    'Lehi',
    'UT',
    40.3918,
    -111.8500,
    ST_SetSRID(ST_MakePoint(-111.8500, 40.3918), 4326),
    ARRAY['mvp','launched','traction','fundraising'],
    ARRAY['saas','ai','fintech'],
    ARRAY['vc','seed']
  ),
  (
    'Pelion Venture Partners',
    'investor',
    'Venture capital firm supporting early and growth-stage companies.',
    'https://pelionvp.com',
    'Salt Lake City',
    'UT',
    40.7594,
    -111.8935,
    ST_SetSRID(ST_MakePoint(-111.8935, 40.7594), 4326),
    ARRAY['launched','traction','fundraising','scale'],
    ARRAY['saas','enterprise','security'],
    ARRAY['vc','growth']
  )
ON CONFLICT DO NOTHING;
