-- Update all startup profile logos from Brandfetch to Logo.dev
-- Covers all 220 companies with consistent Logo.dev API URLs

WITH logo_updates(name, website, logo_url) AS (
VALUES
  ('3Helix', 'www.3helix.com', 'https://img.logo.dev/3helix.com?size=64&format=png&fallback=404'),
  ('ADDAX Overland', 'www.addaxoverland.com', 'https://img.logo.dev/addaxoverland.com?size=64&format=png&fallback=404'),
  ('Adminify AI', 'adminify.ai', 'https://img.logo.dev/adminify.ai?size=64&format=png&fallback=404'),
  ('After.com', 'www.after.com', 'https://img.logo.dev/after.com?size=64&format=png&fallback=404'),
  ('Airbatch', 'Airbatch.io', 'https://img.logo.dev/airbatch.io?size=64&format=png&fallback=404'),
  ('Alcomy', 'alcomy.com', 'https://img.logo.dev/alcomy.com?size=64&format=png&fallback=404'),
  ('Alcomy', 'www.alcomy.com', 'https://img.logo.dev/alcomy.com?size=64&format=png&fallback=404'),
  ('Alianza', 'www.alianza.com', 'https://img.logo.dev/alianza.com?size=64&format=png&fallback=404'),
  ('alphaMountain', 'www.alphamountain.ai', 'https://img.logo.dev/alphamountain.ai?size=64&format=png&fallback=404'),
  ('Alpyne', 'www.getalpyne.com', 'https://img.logo.dev/getalpyne.com?size=64&format=png&fallback=404'),
  ('Altitude AI', 'www.altitudeai.ai', 'https://img.logo.dev/altitudeai.ai?size=64&format=png&fallback=404'),
  ('Alysio', 'www.alysio.ai', 'https://img.logo.dev/alysio.ai?size=64&format=png&fallback=404'),
  ('American Battery Factory', 'www.americanbatteryfactory.com', 'https://img.logo.dev/americanbatteryfactory.com?size=64&format=png&fallback=404'),
  ('Applause', 'www.applausehq.com', 'https://img.logo.dev/applausehq.com?size=64&format=png&fallback=404'),
  ('AskElephant', 'www.askelephant.ai', 'https://img.logo.dev/askelephant.ai?size=64&format=png&fallback=404'),
  ('Atomic', 'www.atomic.financial', 'https://img.logo.dev/atomic.financial?size=64&format=png&fallback=404'),
  ('Attestiv', 'www.attestiv.com', 'https://img.logo.dev/attestiv.com?size=64&format=png&fallback=404'),
  ('Avy', 'www.avy.ai', 'https://img.logo.dev/avy.ai?size=64&format=png&fallback=404'),
  ('Awardco', 'www.award.co', 'https://img.logo.dev/award.co?size=64&format=png&fallback=404'),
  ('Awsm', 'www.awsm.com', 'https://img.logo.dev/awsm.com?size=64&format=png&fallback=404'),
  ('Bacon', 'www.baconwork.com', 'https://img.logo.dev/baconwork.com?size=64&format=png&fallback=404'),
  ('Bandwango', 'www.bandwango.com', 'https://img.logo.dev/bandwango.com?size=64&format=png&fallback=404'),
  ('Benji Card', 'benjicard.com', 'https://img.logo.dev/benjicard.com?size=64&format=png&fallback=404'),
  ('Blue Eye', 'www.goblueeye.com', 'https://img.logo.dev/goblueeye.com?size=64&format=png&fallback=404'),
  ('BookClub', 'www.bookclub.com', 'https://img.logo.dev/bookclub.com?size=64&format=png&fallback=404'),
  ('Boostly', 'www.boostly.com', 'https://img.logo.dev/boostly.com?size=64&format=png&fallback=404'),
  ('Bracket Labs', 'www.bracket.fi', 'https://img.logo.dev/bracket.fi?size=64&format=png&fallback=404'),
  ('Brite', 'www.britebenefits.com', 'https://img.logo.dev/britebenefits.com?size=64&format=png&fallback=404'),
  ('Brooksee', 'www.brooksee.com', 'https://img.logo.dev/brooksee.com?size=64&format=png&fallback=404'),
  ('Built for Teams', 'www.builtapp.com', 'https://img.logo.dev/builtapp.com?size=64&format=png&fallback=404'),
  ('Canopy Tax', 'www.getcanopy.com', 'https://img.logo.dev/getcanopy.com?size=64&format=png&fallback=404'),
  ('Cardagraph', 'www.cardagraph.com', 'https://img.logo.dev/cardagraph.com?size=64&format=png&fallback=404'),
  ('Carketa', 'carketa.com', 'https://img.logo.dev/carketa.com?size=64&format=png&fallback=404'),
  ('Chargezoom', 'www.chargezoom.com', 'https://img.logo.dev/chargezoom.com?size=64&format=png&fallback=404'),
  ('Cinch', 'www.cinch.io', 'https://img.logo.dev/cinch.io?size=64&format=png&fallback=404'),
  ('Clientbook', 'www.clientbook.com', 'https://img.logo.dev/clientbook.com?size=64&format=png&fallback=404'),
  ('Cloud Storage Security', 'cloudstoragesecurity.com', 'https://img.logo.dev/cloudstoragesecurity.com?size=64&format=png&fallback=404'),
  ('Continuum', 'joincontinuum.com', 'https://img.logo.dev/joincontinuum.com?size=64&format=png&fallback=404'),
  ('ControlQore', 'www.controlqore.com', 'https://img.logo.dev/controlqore.com?size=64&format=png&fallback=404'),
  ('Cotopaxi', 'www.cotopaski.com', 'https://img.logo.dev/cotopaski.com?size=64&format=png&fallback=404'),
  ('Cove', 'covesmart.com', 'https://img.logo.dev/covesmart.com?size=64&format=png&fallback=404'),
  ('Crew', 'www.trycrew.com', 'https://img.logo.dev/trycrew.com?size=64&format=png&fallback=404'),
  ('Cupbop', 'www.cupbop.com', 'https://img.logo.dev/cupbop.com?size=64&format=png&fallback=404'),
  ('Data Quality Co-Op', 'www.dataqualityco-op.com', 'https://img.logo.dev/dataqualityco-op.com?size=64&format=png&fallback=404'),
  ('DeepPower', 'www.deeppower.com', 'https://img.logo.dev/deeppower.com?size=64&format=png&fallback=404'),
  ('DeepSee', 'deepsee.ai', 'https://img.logo.dev/deepsee.ai?size=64&format=png&fallback=404'),
  ('Devote', 'usedevote.com', 'https://img.logo.dev/usedevote.com?size=64&format=png&fallback=404'),
  ('Distro', 'distro.io', 'https://img.logo.dev/distro.io?size=64&format=png&fallback=404'),
  ('Domus Diagnostics', 'www.domusdx.com', 'https://img.logo.dev/domusdx.com?size=64&format=png&fallback=404'),
  ('Dónde', 'www.godonde.com', 'https://img.logo.dev/godonde.com?size=64&format=png&fallback=404'),
  ('Dorai', 'www.doraihome.com', 'https://img.logo.dev/doraihome.com?size=64&format=png&fallback=404'),
  ('dree', 'www.dree.com', 'https://img.logo.dev/dree.com?size=64&format=png&fallback=404'),
  ('Driven', 'pestiq.webflow.io', 'https://img.logo.dev/pestiq.webflow.io?size=64&format=png&fallback=404'),
  ('Droplet', 'www.droplet.io', 'https://img.logo.dev/droplet.io?size=64&format=png&fallback=404'),
  ('DrumCV', 'www.drumcv.com', 'https://img.logo.dev/drumcv.com?size=64&format=png&fallback=404'),
  ('EagleCorps', 'www.eaglecorps.com', 'https://img.logo.dev/eaglecorps.com?size=64&format=png&fallback=404'),
  ('Ednition', 'www.ednition.com', 'https://img.logo.dev/ednition.com?size=64&format=png&fallback=404'),
  ('Elektrik App Inc', 'Elektrikapp.com', 'https://img.logo.dev/elektrikapp.com?size=64&format=png&fallback=404'),
  ('Elements', 'www.getelements.com', 'https://img.logo.dev/getelements.com?size=64&format=png&fallback=404'),
  ('ElizaChat', 'elizachat.com', 'https://img.logo.dev/elizachat.com?size=64&format=png&fallback=404'),
  ('Ember', 'www.emberhome.com', 'https://img.logo.dev/emberhome.com?size=64&format=png&fallback=404'),
  ('Enzo Health', 'www.enzo.health', 'https://img.logo.dev/enzo.health?size=64&format=png&fallback=404'),
  ('Errand', 'www.goerrand.com', 'https://img.logo.dev/goerrand.com?size=64&format=png&fallback=404'),
  ('Filevine', 'www.filevine.com', 'https://img.logo.dev/filevine.com?size=64&format=png&fallback=404'),
  ('Flowell', 'www.flowell.co', 'https://img.logo.dev/flowell.co?size=64&format=png&fallback=404'),
  ('FluentWorlds', 'www.fluentworlds.com', 'https://img.logo.dev/fluentworlds.com?size=64&format=png&fallback=404'),
  ('Fluid', 'www.fluid.app', 'https://img.logo.dev/fluid.app?size=64&format=png&fallback=404'),
  ('Funner', 'www.funner.com', 'https://img.logo.dev/funner.com?size=64&format=png&fallback=404'),
  ('Gabb Wireless', 'www.gabb.com', 'https://img.logo.dev/gabb.com?size=64&format=png&fallback=404'),
  ('Gauge', 'www.sellgauge.com', 'https://img.logo.dev/sellgauge.com?size=64&format=png&fallback=404'),
  ('Giddy', 'www.giddy.co', 'https://img.logo.dev/giddy.co?size=64&format=png&fallback=404'),
  ('Grain', 'grain.com', 'https://img.logo.dev/grain.com?size=64&format=png&fallback=404'),
  ('Guard IQ', 'GuardIQ.com', 'https://img.logo.dev/guardiq.com?size=64&format=png&fallback=404'),
  ('Halda', 'www.halda.ai', 'https://img.logo.dev/halda.ai?size=64&format=png&fallback=404'),
  ('Halosight', 'www.halosight.com', 'https://img.logo.dev/halosight.com?size=64&format=png&fallback=404'),
  ('Helperly', 'helperly.com', 'https://img.logo.dev/helperly.com?size=64&format=png&fallback=404'),
  ('HeroDevs', 'www.herodevs.com', 'https://img.logo.dev/herodevs.com?size=64&format=png&fallback=404'),
  ('Homie', 'www.homie.com', 'https://img.logo.dev/homie.com?size=64&format=png&fallback=404'),
  ('Hona', 'www.hona.com', 'https://img.logo.dev/hona.com?size=64&format=png&fallback=404'),
  ('Hypercraft', 'www.hypercraftusa.com', 'https://img.logo.dev/hypercraftusa.com?size=64&format=png&fallback=404'),
  ('iDrive Logistics', 'www.idrivelogistics.com', 'https://img.logo.dev/idrivelogistics.com?size=64&format=png&fallback=404'),
  ('Inherent Biosciences', 'www.inherentbio.com', 'https://img.logo.dev/inherentbio.com?size=64&format=png&fallback=404'),
  ('IsoTalent', 'www.isotalent.com', 'https://img.logo.dev/isotalent.com?size=64&format=png&fallback=404'),
  ('Jipe', 'www.jipejobs.com', 'https://img.logo.dev/jipejobs.com?size=64&format=png&fallback=404'),
  ('JobNimbus', 'www.jobnimbus.com', 'https://img.logo.dev/jobnimbus.com?size=64&format=png&fallback=404'),
  ('Jump', 'jumpapp.com', 'https://img.logo.dev/jumpapp.com?size=64&format=png&fallback=404'),
  ('KetoNatural Pet Foods', 'www.ketonaturalpetfoods.com', 'https://img.logo.dev/ketonaturalpetfoods.com?size=64&format=png&fallback=404'),
  ('Kolla', 'www.getkolla.com', 'https://img.logo.dev/getkolla.com?size=64&format=png&fallback=404'),
  ('Krado', 'www.krado.co', 'https://img.logo.dev/krado.co?size=64&format=png&fallback=404'),
  ('Kuali', 'www.kuali.co', 'https://img.logo.dev/kuali.co?size=64&format=png&fallback=404'),
  ('Learnie', 'mylearnie.com', 'https://img.logo.dev/mylearnie.com?size=64&format=png&fallback=404'),
  ('Leash Bio', 'www.leash.bio', 'https://img.logo.dev/leash.bio?size=64&format=png&fallback=404'),
  ('Leeway', 'www.leewayhq.com', 'https://img.logo.dev/leewayhq.com?size=64&format=png&fallback=404'),
  ('Leland', 'www.joinleland.com', 'https://img.logo.dev/joinleland.com?size=64&format=png&fallback=404'),
  ('Lendio', 'www.lendio.com', 'https://img.logo.dev/lendio.com?size=64&format=png&fallback=404'),
  ('Limit Break', 'www.limitbreak.com', 'https://img.logo.dev/limitbreak.com?size=64&format=png&fallback=404'),
  ('Listo Global', 'Listoglobal.com', 'https://img.logo.dev/listoglobal.com?size=64&format=png&fallback=404'),
  ('Literal', 'www.literalapp.com', 'https://img.logo.dev/literalapp.com?size=64&format=png&fallback=404'),
  ('Liveview Technologies', 'www.lvt.com', 'https://img.logo.dev/lvt.com?size=64&format=png&fallback=404'),
  ('LooLoo', 'www.getlooloo.com', 'https://img.logo.dev/getlooloo.com?size=64&format=png&fallback=404'),
  ('Lucid', 'lucid.co', 'https://img.logo.dev/lucid.co?size=64&format=png&fallback=404'),
  ('Mallow', 'www.getmallow.com', 'https://img.logo.dev/getmallow.com?size=64&format=png&fallback=404'),
  ('Masset', 'www.getmasset.com', 'https://img.logo.dev/getmasset.com?size=64&format=png&fallback=404'),
  ('Metrodora Institute', 'www.metrodora.co', 'https://img.logo.dev/metrodora.co?size=64&format=png&fallback=404'),
  ('Mindless Labs', 'mindless.org', 'https://img.logo.dev/mindless.org?size=64&format=png&fallback=404'),
  ('Mindsmith', 'www.mindsmith.ai', 'https://img.logo.dev/mindsmith.ai?size=64&format=png&fallback=404'),
  ('Mobly', 'www.getmobly.com', 'https://img.logo.dev/getmobly.com?size=64&format=png&fallback=404'),
  ('Modal Living', 'www.livemodal.com', 'https://img.logo.dev/livemodal.com?size=64&format=png&fallback=404'),
  ('Monarx', 'www.monarx.com', 'https://img.logo.dev/monarx.com?size=64&format=png&fallback=404'),
  ('Moneta', 'www.monetacloud.com', 'https://img.logo.dev/monetacloud.com?size=64&format=png&fallback=404'),
  ('Monovo', 'monovo.care', 'https://img.logo.dev/monovo.care?size=64&format=png&fallback=404'),
  ('MotionOps', 'www.motionops.com', 'https://img.logo.dev/motionops.com?size=64&format=png&fallback=404'),
  ('Motivhealth', 'www.motivhealth.com', 'https://img.logo.dev/motivhealth.com?size=64&format=png&fallback=404'),
  ('Murf', 'www.murf.ai', 'https://img.logo.dev/murf.ai?size=64&format=png&fallback=404'),
  ('Music AI', 'www.music.ai', 'https://img.logo.dev/music.ai?size=64&format=png&fallback=404'),
  ('MX', 'www.mx.com', 'https://img.logo.dev/mx.com?size=64&format=png&fallback=404'),
  ('NanoSpot.ai', 'www.nanospot.ai', 'https://img.logo.dev/nanospot.ai?size=64&format=png&fallback=404'),
  ('Nectar HR', 'www.nectarhr.com', 'https://img.logo.dev/nectarhr.com?size=64&format=png&fallback=404'),
  ('Neighbor', 'www.neighbor.com', 'https://img.logo.dev/neighbor.com?size=64&format=png&fallback=404'),
  ('Neighbor', 'neighbor.com', 'https://img.logo.dev/neighbor.com?size=64&format=png&fallback=404'),
  ('Nivati', 'www.nivati.com', 'https://img.logo.dev/nivati.com?size=64&format=png&fallback=404'),
  ('Nodal Power', 'www.nodalpower.com', 'https://img.logo.dev/nodalpower.com?size=64&format=png&fallback=404'),
  ('Nodal Power Inc', 'nodalpowersystems.com', 'https://img.logo.dev/nodalpowersystems.com?size=64&format=png&fallback=404'),
  ('Nomi Health', 'www.nomihealth.com', 'https://img.logo.dev/nomihealth.com?size=64&format=png&fallback=404'),
  ('Nomyx', 'www.nomyx.io', 'https://img.logo.dev/nomyx.io?size=64&format=png&fallback=404'),
  ('Nursa', 'www.nursa.com', 'https://img.logo.dev/nursa.com?size=64&format=png&fallback=404'),
  ('ObservePoint', 'www.observepoint.com', 'https://img.logo.dev/observepoint.com?size=64&format=png&fallback=404'),
  ('Oka', 'carboninsurance.co', 'https://img.logo.dev/carboninsurance.co?size=64&format=png&fallback=404'),
  ('Oliver IQ', 'www.oliveriq.com', 'https://img.logo.dev/oliveriq.com?size=64&format=png&fallback=404'),
  ('Olumo', 'www.olumo.com', 'https://img.logo.dev/olumo.com?size=64&format=png&fallback=404'),
  ('Ovation', 'www.ovationup.com', 'https://img.logo.dev/ovationup.com?size=64&format=png&fallback=404'),
  ('Pageport', 'www.pageport.com', 'https://img.logo.dev/pageport.com?size=64&format=png&fallback=404'),
  ('Paiv', 'www.paiv.ai', 'https://img.logo.dev/paiv.ai?size=64&format=png&fallback=404'),
  ('Pale Blue', 'www.paleblueearth.com', 'https://img.logo.dev/paleblueearth.com?size=64&format=png&fallback=404'),
  ('Parakeet Financial', 'www.parakeetfinancial.com', 'https://img.logo.dev/parakeetfinancial.com?size=64&format=png&fallback=404'),
  ('Parallel', 'getparallel.com', 'https://img.logo.dev/getparallel.com?size=64&format=png&fallback=404'),
  ('Paramify', 'www.paramify.com', 'https://img.logo.dev/paramify.com?size=64&format=png&fallback=404'),
  ('Particl', 'www.particl.com', 'https://img.logo.dev/particl.com?size=64&format=png&fallback=404'),
  ('Paterna BioSciences', 'www.paternabio.com', 'https://img.logo.dev/paternabio.com?size=64&format=png&fallback=404'),
  ('Paykeeper', 'www.paykeeper.com', 'https://img.logo.dev/paykeeper.com?size=64&format=png&fallback=404'),
  ('Pestie', 'www.pestie.com', 'https://img.logo.dev/pestie.com?size=64&format=png&fallback=404'),
  ('Pillow Cube', 'www.pillowcube.com', 'https://img.logo.dev/pillowcube.com?size=64&format=png&fallback=404'),
  ('Plansight', 'www.plansight.com', 'https://img.logo.dev/plansight.com?size=64&format=png&fallback=404'),
  ('Plotline', 'www.plotline.so', 'https://img.logo.dev/plotline.so?size=64&format=png&fallback=404'),
  ('Pocketbook', 'pocketbk.com', 'https://img.logo.dev/pocketbk.com?size=64&format=png&fallback=404'),
  ('Powder Watts', 'www.powderwatts.com', 'https://img.logo.dev/powderwatts.com?size=64&format=png&fallback=404'),
  ('PowerBx', 'powerbx.com', 'https://img.logo.dev/powerbx.com?size=64&format=png&fallback=404'),
  ('Previ', 'previ.com', 'https://img.logo.dev/previ.com?size=64&format=png&fallback=404'),
  ('Project Solar', 'www.projectsolar.com', 'https://img.logo.dev/projectsolar.com?size=64&format=png&fallback=404'),
  ('Pura', 'www.pura.com', 'https://img.logo.dev/pura.com?size=64&format=png&fallback=404'),
  ('Pyrofex', 'pyrofex.net', 'https://img.logo.dev/pyrofex.net?size=64&format=png&fallback=404'),
  ('Qualiti', 'www.qualiti.ai', 'https://img.logo.dev/qualiti.ai?size=64&format=png&fallback=404'),
  ('Rasa', 'www.rasa-legal.com', 'https://img.logo.dev/rasa-legal.com?size=64&format=png&fallback=404'),
  ('Redo', 'www.getredo.com', 'https://img.logo.dev/getredo.com?size=64&format=png&fallback=404'),
  ('Referpro', 'referpro.co', 'https://img.logo.dev/referpro.co?size=64&format=png&fallback=404'),
  ('ReferPro', 'www.getrefer.pro', 'https://img.logo.dev/getrefer.pro?size=64&format=png&fallback=404'),
  ('Relay Health', 'www.joinrelay.app', 'https://img.logo.dev/joinrelay.app?size=64&format=png&fallback=404'),
  ('Remi', 'www.remihq.com', 'https://img.logo.dev/remihq.com?size=64&format=png&fallback=404'),
  ('Renew Biotechnologies', 'www.renewbt.com', 'https://img.logo.dev/renewbt.com?size=64&format=png&fallback=404'),
  ('Ripe', 'bookripe.com', 'https://img.logo.dev/bookripe.com?size=64&format=png&fallback=404'),
  ('Rivet Health', 'www.rivethealth.com', 'https://img.logo.dev/rivethealth.com?size=64&format=png&fallback=404'),
  ('Roger', 'www.tryroger.com', 'https://img.logo.dev/tryroger.com?size=64&format=png&fallback=404'),
  ('Roster', 'www.getroster.com', 'https://img.logo.dev/getroster.com?size=64&format=png&fallback=404'),
  ('Route', 'www.route.com', 'https://img.logo.dev/route.com?size=64&format=png&fallback=404'),
  ('SABX', 'www.sabx.com', 'https://img.logo.dev/sabx.com?size=64&format=png&fallback=404'),
  ('Safety Mojo', 'www.getmojo.ai', 'https://img.logo.dev/getmojo.ai?size=64&format=png&fallback=404'),
  ('Salad', 'www.salad.com', 'https://img.logo.dev/salad.com?size=64&format=png&fallback=404'),
  ('SalesRabbit', 'salesrabbit.com', 'https://img.logo.dev/salesrabbit.com?size=64&format=png&fallback=404'),
  ('Sameday', 'gosameday.com', 'https://img.logo.dev/gosameday.com?size=64&format=png&fallback=404'),
  ('Savvos', 'www.savvos.com', 'https://img.logo.dev/savvos.com?size=64&format=png&fallback=404'),
  ('SchoolAI', 'www.schoolai.com', 'https://img.logo.dev/schoolai.com?size=64&format=png&fallback=404'),
  ('Seis', 'www.seis.com', 'https://img.logo.dev/seis.com?size=64&format=png&fallback=404'),
  ('SignalHero', 'www.signalhero.io', 'https://img.logo.dev/signalhero.io?size=64&format=png&fallback=404'),
  ('Skill Struck', 'www.skillstruck.com', 'https://img.logo.dev/skillstruck.com?size=64&format=png&fallback=404'),
  ('Slipstream Medical', 'www.slipstreammedical.com', 'https://img.logo.dev/slipstreammedical.com?size=64&format=png&fallback=404'),
  ('Snoball', 'snoball.com', 'https://img.logo.dev/snoball.com?size=64&format=png&fallback=404'),
  ('Solo', 'www.gosolo.io', 'https://img.logo.dev/gosolo.io?size=64&format=png&fallback=404'),
  ('Solo', 'solosuit.com', 'https://img.logo.dev/solosuit.com?size=64&format=png&fallback=404'),
  ('SpaceAgent', 'spaceagent.app', 'https://img.logo.dev/spaceagent.app?size=64&format=png&fallback=404'),
  ('SponsorCX', 'sponsorcx.com', 'https://img.logo.dev/sponsorcx.com?size=64&format=png&fallback=404'),
  ('SquarePeg', 'www.squarepeghires.com', 'https://img.logo.dev/squarepeghires.com?size=64&format=png&fallback=404'),
  ('Stay AI', 'www.stay.ai', 'https://img.logo.dev/stay.ai?size=64&format=png&fallback=404'),
  ('StreamOS', 'www.streamos.io', 'https://img.logo.dev/streamos.io?size=64&format=png&fallback=404'),
  ('Strider', 'www.striderintel.com', 'https://img.logo.dev/striderintel.com?size=64&format=png&fallback=404'),
  ('stumbl', 'www.stumbl.com', 'https://img.logo.dev/stumbl.com?size=64&format=png&fallback=404'),
  ('Swell', 'www.swellcx.com', 'https://img.logo.dev/swellcx.com?size=64&format=png&fallback=404'),
  ('Swyf', 'www.swyf.app', 'https://img.logo.dev/swyf.app?size=64&format=png&fallback=404'),
  ('Syncware', 'www.syncware.com', 'https://img.logo.dev/syncware.com?size=64&format=png&fallback=404'),
  ('Tava Health', 'www.tavahealth.com', 'https://img.logo.dev/tavahealth.com?size=64&format=png&fallback=404'),
  ('Tellus', 'www.tellusensors.com', 'https://img.logo.dev/tellusensors.com?size=64&format=png&fallback=404'),
  ('Territories.AI', 'territories.ai', 'https://img.logo.dev/territories.ai?size=64&format=png&fallback=404'),
  ('The Picklr', 'www.thepicklr.com', 'https://img.logo.dev/thepicklr.com?size=64&format=png&fallback=404'),
  ('TheraPro.ai', 'therapro.ai', 'https://img.logo.dev/therapro.ai?size=64&format=png&fallback=404'),
  ('Thymeless Enterprises', 'rosierue.com', 'https://img.logo.dev/rosierue.com?size=64&format=png&fallback=404'),
  ('Torus', 'www.torus.co', 'https://img.logo.dev/torus.co?size=64&format=png&fallback=404'),
  ('Treads', 'www.treads.app', 'https://img.logo.dev/treads.app?size=64&format=png&fallback=404'),
  ('Trinsic', 'trinsic.id', 'https://img.logo.dev/trinsic.id?size=64&format=png&fallback=404'),
  ('Troomi', 'www.troomi.com', 'https://img.logo.dev/troomi.com?size=64&format=png&fallback=404'),
  ('Upkid', 'www.upkid.com', 'https://img.logo.dev/upkid.com?size=64&format=png&fallback=404'),
  ('Vanderhall', 'www.vanderhallusa.com', 'https://img.logo.dev/vanderhallusa.com?size=64&format=png&fallback=404'),
  ('Vanilla', 'www.justvanilla.com', 'https://img.logo.dev/justvanilla.com?size=64&format=png&fallback=404'),
  ('Vasion', 'vasion.com', 'https://img.logo.dev/vasion.com?size=64&format=png&fallback=404'),
  ('Velocity Access', 'www.velocityaccess.io', 'https://img.logo.dev/velocityaccess.io?size=64&format=png&fallback=404'),
  ('Velosimo', 'www.velosimo.com', 'https://img.logo.dev/velosimo.com?size=64&format=png&fallback=404'),
  ('Veras', 'www.jobwise.com', 'https://img.logo.dev/jobwise.com?size=64&format=png&fallback=404'),
  ('Videra Health', 'www.viderahealth.com', 'https://img.logo.dev/viderahealth.com?size=64&format=png&fallback=404'),
  ('Viori', 'www.viori.com', 'https://img.logo.dev/viori.com?size=64&format=png&fallback=404'),
  ('VIUS', 'viusbuilt.com', 'https://img.logo.dev/viusbuilt.com?size=64&format=png&fallback=404'),
  ('Voze', 'www.voze.com', 'https://img.logo.dev/voze.com?size=64&format=png&fallback=404'),
  ('Wander', 'www.wandermaps.com', 'https://img.logo.dev/wandermaps.com?size=64&format=png&fallback=404'),
  ('Wasatch BioLabs', 'www.wasatchbiolabs.com', 'https://img.logo.dev/wasatchbiolabs.com?size=64&format=png&fallback=404'),
  ('Whistic', 'whistic.com', 'https://img.logo.dev/whistic.com?size=64&format=png&fallback=404'),
  ('Xenter', 'www.xenter.io', 'https://img.logo.dev/xenter.io?size=64&format=png&fallback=404'),
  ('Xevant', 'www.xevant.com', 'https://img.logo.dev/xevant.com?size=64&format=png&fallback=404'),
  ('Yoodlize', 'www.yoodlize.com', 'https://img.logo.dev/yoodlize.com?size=64&format=png&fallback=404'),
  ('Zanskar', 'www.zanskar.com', 'https://img.logo.dev/zanskar.com?size=64&format=png&fallback=404'),
  ('Zapmoto', 'www.zapmoto.com', 'https://img.logo.dev/zapmoto.com?size=64&format=png&fallback=404'),
  ('Zartico', 'www.zartico.com', 'https://img.logo.dev/zartico.com?size=64&format=png&fallback=404'),
  ('Zaymo', 'www.zaymo.com', 'https://img.logo.dev/zaymo.com?size=64&format=png&fallback=404'),
  ('Zonos', 'zonos.com', 'https://img.logo.dev/zonos.com?size=64&format=png&fallback=404')
)
UPDATE startup_profiles sp
SET
  logo_url = lu.logo_url,
  updated_at = NOW()
FROM logo_updates lu
WHERE sp.name = lu.name
  AND sp.website IS NOT DISTINCT FROM lu.website;
